name: upnp
version: 1.0.0
author: Kenneth Endfinger <kaendfinger@gmail.com>
description: Universal Plugin and Play Client
homepage: https://github.com/DirectMyFile/upnp.dart
environment:
  sdk: ">=2.0.0-dev.61.0 <3.0.0"
dependencies:
  http: ">=0.11.1 <0.12.0"
  quiver: "^2.0.0+1"
  xml: "^3.2.0"
  stack_trace: "^1.6.5"
  crypto: "^2.0.1"
  logging: "^0.11.3+1"
